export const SomeProjects = [
  { name: "Seeding",
    isLive: true,
    description: "A personal habit tracker and growth companion that helps you build positive habits through gentle reminders and visual growth metaphors. Watch your digital seed grow from a tiny sprout into a mighty tree as you maintain your streaks. Your data stays private and offline, right on your device.",
    status: "Live on Play Store",
    tags: ["React Native", "ExpoGo", "Mobile Development"],
    link: {playStore: "https://play.google.com/store/apps/details?id=com.seeding.app"},
    category: "Mobile Development",
    featured: true,
    legendary: true
  },
  { name: "PFS Magnets",
    isLive: true,
    description: "Created an elegant website designed for selling beautifully crafted magnets in customized and specific sizes. With a stunning UI, it provides a seamless experience for users to purchase personalized magnets that reflect their unique style and personality.",
    status: "Work In Progress",
    tags: ["React", "React-Router", "TailwindCSS", "TypeScript", "Shadcn"],
    link: {github: "https://pfs-magnets.vercel.app/"},
    category: "Full-Stack Development",
    featured: true
  },
  { name: "WordSmith",
    isLive: true,
    description: "WordSmith is a user-friendly blogging platform designed with an elegant and visually appealing aesthetic. Built using RemixJS and React, it offers a seamless and engaging experience for both writers and readers.",
    status: "Archived (Live)",
    tags: ["React", "RemixJS", "TailwindCSS", "Prisma", "PostgreSQL", "NextUI", "TypeScript"],
    link: {github: "https://github.com/fudge-fantastic/WordSmith"},
    category: "Full-Stack Development",
    featured: true
  },
  { name: "Portfolio V0.1",
    isLive: false,
    description: "Developed a dynamic portfolio website using HTML, CSS, and JavaScript, integrated with Django for robust backend functionality.",
    status: "Closed",
    tags: ["HTML", "CSS", "JavaScript", "Django"],
    link: {github: "https://github.com/fudge-fantastic/Portfolio_V0.1_CLOSED"},
    category: "Web Development",
    featured: false
  },
  { name: "LeetCode Solutions",
    isLive: false,
    description: "Grinding Leetcode problems like a maniac—half to impress those big tech overlords, half to untangle the mess I call logic. It's me vs. algorithms, one brain cell at a time, we're making progress!",
    status: "Archived",
    tags: ["Python"],
    link: {github: "https://github.com/fudge-fantastic/CLeet"},
    category: "Competitive Programming",
    featured: false
  },
  { name: "Kaizen (改善)",
    isLive: false,
    description: "Trained models, slapped them into a Flask suit, boxed it all up with Docker, and let Jenkins handle the dirty CI/CD work. GitHub webhooks kept it smooth, and I babysat it with Prometheus—because even AI needs hand-holding sometimes.",
    status: "Closed",
    tags: ["Python", "FastAPI", "Flask", "MLFlow", "Jenkins", "Docker", "CI/CD", "AWS"],
    link: {github: "https://github.com/fudge-fantastic/Kaizen_CLOSED"},
    category: "DevOps & MLOps",
    featured: true
  },
  { name: "Machine Learning",
    isLive: false,
    description: "Spent my days making machines classify and regress—mini-projects that screamed 'predict this!' and 'analyze that!' Crunching data, running stats, and building predictive models like a caffeinated fortune teller with a knack for spreadsheets.",
    status: "Archived",
    tags: ["Python", "Data Analytics", "Statistical Analysis"],
    link: {github: "https://github.com/fudge-fantastic/Machine_Learning"},
    category: "AI & ML",
    featured: false
  },
];
