export const SomeProjects = [
  { name: "GitTalk",
    isLive: false, 
    description: "GitTalk lets you chat with GitHub repositories — ask questions, get insights, and understand code instantly. Whether it's a single file or the whole repo, GitTalk turns your GitHub projects into conversational partners.", 
    status: "Work In Progress", 
    tags: ["React", "RemixJS", "TailwindCSS", "Prisma", "PostgreSQL", "TypeScript", "Langchain", "Qdrant/Weaviate", "Large Language Models"],
    link: {github: "https://github.com/fudge-fantastic/GitTalk_V2"},
    category: "Full-Stack Development",
    featured: true
  },
  { name: "WordSmith",
    isLive: true, 
    description: "WordSmith is a user-friendly blogging platform designed with an elegant and visually appealing aesthetic. Built using RemixJS and React, it offers a seamless and engaging experience for both writers and readers.", 
    status: "Archived (Live)", 
    tags: ["React", "RemixJS", "TailwindCSS", "Prisma", "PostgreSQL", "NextUI", "TypeScript"],
    link: {github: "https://github.com/fudge-fantastic/WordSmith"},
    category: "Full-Stack Development",
    featured: true
  },
  { name: "Portfolio V0.1",
    isLive: false, 
    description: "Developed a dynamic portfolio website using HTML, CSS, and JavaScript, integrated with Django for robust backend functionality.", 
    status: "Closed", 
    tags: ["HTML", "CSS", "JavaScript", "Django"],
    link: {github: "https://github.com/fudge-fantastic/Portfolio_V0.1_CLOSED"},
    category: "Web Development",
    featured: false
  },
  { name: "Query Forge",
    isLive: false, 
    description: "Developed a tool leveraging LangChain, Hugging Face models, and Qdrant VectorDB for efficient website summarization by extracting and retrieving semantically similar content based on a provided URL.", 
    status: "Archived", 
    tags: ["React", "RemixJS", "TailwindCSS", "QDrant", "Langchain", "NextUI", "Huggingface", "Python", "JavaScript", "Large Language Models"],
    link: {github: "https://github.com/fudge-fantastic/QueryForge"},
    category: "AI & ML",
    featured: false 
  },
  { name: "LeetCode Solutions",
    isLive: false, 
    description: "Grinding Leetcode problems like a maniac—half to impress those big tech overlords, half to untangle the mess I call logic. It's me vs. algorithms, one brain cell at a time, we’re making progress!", 
    status: "Archived", 
    tags: ["Python"],
    link: {github: "https://github.com/fudge-fantastic/CLeet"},
    category: "Competitive Programming",
    featured: false
  },
  { name: "Kaizen (改善)",
    isLive: false, 
    description: "Trained models, slapped them into a Flask suit, boxed it all up with Docker, and let Jenkins handle the dirty CI/CD work. GitHub webhooks kept it smooth, and I babysat it with Prometheus—because even AI needs hand-holding sometimes.", 
    status: "Closed", 
    tags: ["Python", "FastAPI", "Flask", "MLFlow", "Jenkins", "Docker", "CI/CD", "AWS"],
    link: {github: "https://github.com/fudge-fantastic/Kaizen_CLOSED"},
    category: "DevOps & MLOps",
    featured: true
  },
  { name: "Machine Learning",
    isLive: false, 
    description: "Spent my days making machines classify and regress—mini-projects that screamed ‘predict this!’ and ‘analyze that!’ Crunching data, running stats, and building predictive models like a caffeinated fortune teller with a knack for spreadsheets.", 
    status: "Archived", 
    tags: ["Python", "Data Analytics", "Statistical Analysis"],
    link: {github: "https://github.com/fudge-fantastic/Machine_Learning"},
    category: "AI & ML",
    featured: false
  },
  { name: "Deep Learning",
    description: "Trained models to recognize patterns like a digital detective, tweaking layers until they finally stopped crying. It’s all about pushing pixels, tweaking weights, and hoping the AI doesn’t start questioning its own existence.",
    status: "Archived",
    tags: ["Python", "Tensorflow", "PyTorch", "Computer Vision"],
    link: {github: "https://github.com/fudge-fantastic/Deep_Learning"},
    category: "AI & ML",
    featured: false
  }
];